export const FETCH_COMING_MOVIES = 'FETCH_COMING_MOVIES';
export const RECEIVE_COMING_MOVIES = 'RECEIVE_COMING_MOVIES';
export const SEARCH_COMING_MOVIES = 'SEARCH_COMING_MOVIES';
export const COMING_MOVIES_ERRORS = 'COMING_MOVIES_ERRORS';
