export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const RECEIVE_SESSIONS = 'RECEIVE_SESSIONS';
export const SESSIONS_ERRORS = 'SESSIONS_ERRORS';
export const FILTER_SESSIONS = 'FILTER_SESSIONS';
